# ansible/05-cluster-base/defaults/main.yml
---
pacotes_kubernetes:
  - kernel-modules-extra
  - iproute
  - iptables
  - iptables-nft
  - ethtool
  - socat
  - conntrack-tools
  - ipvsadm
  - ipset
  - tar
  - xz

