# ansible/05-cluster-base/defaults/main.yml
---
pacotes_kubernetes:
  - kernel-modules-extra
  - iproute
  - nftables
  - iptables
  - iptables-nft
  - conntrack-tools
  - ethtool
  - socat
  - tar
  - xz

modulos_kernel_kubernetes:
  - overlay
  - br_netfilter
  - vxlan
  - ip_tables
  - ip6_tables
  - nf_tables
  - nf_nat
  - nf_conntrack
  - xt_conntrack
