# ansible/10-kubelet/tasks/07-instalacao-pause-container.yml
---
- name: Verificar se imagem pause jÃ¡ existe
  ansible.builtin.command:
    cmd: "crictl images -q registry.k8s.io/{{ versao_pause }}"
  register: runtime_imagens
  changed_when: false

- name: Baixar imagem pause
  ansible.builtin.command:
    cmd: "crictl pull registry.k8s.io/{{ versao_pause }}"
  when: "'registry.k8s.io/' ~ versao_pause not in runtime_imagens.stdout_lines"
  changed_when: true
