# ansible/01-pki/tasks/224-cert-admin-account.yml
---
- name: Verificar arquivos existentes da chave para o Admin Account
  ansible.builtin.stat:
    path: "{{ arquivo }}"
  loop:
    - "{{ pki_certs.admin_account.path_chave }}"
    - "{{ pki_certs.admin_account.path_cert }}"
  loop_control:
    loop_var: arquivo
    label: "{{ arquivo | relpath(playbook_dir) }}"
  register: admin_account_arquivos
  delegate_to: localhost

- name: Criar chave privada do certificado para o Admin Account
  community.crypto.openssl_privatekey:
    path: "{{ pki_certs.admin_account.path_chave }}"
    type: "{{ pki_cifra_tipo }}"
    curve: "{{ pki_cifra_algo }}"
    state: "present"
    force: true
  when: not admin_account_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost

- name: Gerar CSR do certificado para o Admin Account
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ pki_certs.admin_account.path_chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    subject:
        O: system:masters
        CN: kubernetes-super-admin
    use_common_name_for_san: false
    basic_constraints:
      - "CA:FALSE"
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
  when: not admin_account_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost
  register: admin_account_csr

- name: Assinar certificado para o Admin Account com o respectivo CA intermedi√°rio
  community.crypto.x509_certificate:
    path: "{{ pki_certs.admin_account.path_cert }}"
    csr_content: "{{ admin_account_csr.csr }}"
    provider: ownca
    ownca_path: "{{ pki_certs.admin_account.ca_pai.path_cert }}"
    ownca_privatekey_path: "{{ pki_certs.admin_account.ca_pai.path_chave }}"
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_not_after: "+{{ pki_validade.certificado | default(30) }}d"
    mode: "0644"
    force: true
  when: not admin_account_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost
