apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contador-pvc
  namespace: exemplos
  labels:
    app: contador-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: servidor-nfs
