apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador
  namespace: exemplos
  labels:
    app: contador-app
    componente: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contador-app
      componente: web
  template:
    metadata:
      labels:
        app: contador-app
        componente: web
    spec:
      serviceAccountName: exemplos-sa
      containers:
        - name: php
          image: php:8.5-apache
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: pagina
              mountPath: /var/www/html
            - name: dados
              mountPath: /dados
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pagina
          configMap:
            name: contador-pagina
        - name: dados
          persistentVolumeClaim:
            claimName: contador-pvc
