apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador
  namespace: exemplos
  labels:
    app: contador-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contador-app
  template:
    metadata:
      labels:
        app: contador-app
    spec:
      containers:
        - name: php
          image: php:8.5-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pagina
              mountPath: /var/www/html
            - name: dados
              mountPath: /dados
      volumes:
        - name: pagina
          configMap:
            name: contador-pagina
        - name: dados
          persistentVolumeClaim:
            claimName: contador-pvc
