apiVersion: v1
kind: Service
metadata:
  name: contador-svc
  namespace: exemplos
  labels:
    app: contador-app
spec:
  selector:
    app: contador-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
