apiVersion: v1
kind: Service
metadata:
  name: contador-svc
  namespace: exemplos
  labels:
    app: contador-app
spec:
  selector:
    app: contador-app
    componente: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
