apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: contador-httproute
  namespace: exemplos
  labels:
    app: contador-app
spec:
  parentRefs:
  - name: traefik-gateway-publico
    namespace: traefik
    sectionName: web
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /contador
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: contador-svc
      port: 80
      kind: Service
