# ansible/ca-certs/tasks/2-kubernetes-ca.yml
---
- name: Verifica se os arquivos já existem
  ansible.builtin.stat:
    path: "{{ item }}"
  register: cluster_stats
  loop:
    - /vagrant/arquivos/kubernetes-ca.key
    - /vagrant/arquivos/kubernetes-ca.crt

- name: Gera um arquivo temporário para o CSR do Cluster CA
  ansible.builtin.tempfile:
    state: file
    prefix: k8s_ca
    suffix: csr
  register: temp_file
  when: not cluster_stats.results[0].stat.exists or not cluster_stats.results[1].stat.exists

- name: Gera a chave privada do Cluster CA
  community.crypto.openssl_privatekey:
    path: /vagrant/arquivos/kubernetes-ca.key
    type: "{{ tipo_chave_privada_k8s }}"
    state: present
  when: not cluster_stats.results[0].stat.exists

- name: Gera um CSR para o Cluster CA com as infos necessárias
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:TRUE
    keyUsage_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    common_name: kubernetes-ca
    path: "{{ temp_file.path }}"
    privatekey_path: /vagrant/arquivos/kubernetes-ca.key
    state: present
  when: not cluster_stats.results[0].stat.exists or not cluster_stats.results[1].stat.exists

- name: Gera o certificado do Cluster CA
  community.crypto.x509_certificate:
    path: /vagrant/arquivos/kubernetes-ca.crt
    privatekey_path: /vagrant/arquivos/kubernetes-ca.key
    csr_path: "{{ temp_file.path }}"
    provider: selfsigned
    state: present
    selfsigned_not_before: "-1h"
    selfsigned_not_after: "+365d"
  when: not cluster_stats.results[1].stat.exists