apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: exemplos
  labels:
    app: hello-app
spec:
  selector:
    app: hello-app
    componente: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
