apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: exemplos
  labels:
    app: hello-app
spec:
  selector:
    app: hello-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
