apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-httproute
  namespace: exemplos
  labels:
    app: hello-app
spec:
  parentRefs:
  - name: traefik-gateway-publico
    namespace: traefik
    sectionName: web
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hello-svc
      port: 80
