apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-hpa-teste-stress
  namespace: exemplos
  labels:
    app: hello-app
    componente: cronjob
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: hello-app
        componente: cronjob
    spec:
      ttlSecondsAfterFinished: 1800
      template:
        metadata:
          labels:
            app: hello-app
            componente: cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: fortio
              image: fortio/fortio:1.73.2
              args:
                - load
                - -n  # Ignora com -t, roda até timeout
                - "0"
                - -c
                - "250"      # +150 concurrent
                - -qps       # Rate máximo
                - "2000"     # 2k req/s (pesado!)
                - -t
                - "120s"     # 2min full blast
                - http://hello-svc
              resources:
                requests:
                  cpu: "100m"
                  memory: "64Mi"
                limits:
                  cpu: "1500m"
                  memory: "256Mi"
