# ansible/haproxy/defaults/main.yml
---
# Vers√£o
versao_haproxy: "3.0"

# Timeouts
timeout_connect: 30s
timeout_client: 30s
timeout_server: 30s

# Credenciais
haproxy_stats_usr: "admin"
haproxy_stats_senha: "senha_muito_segura!"

# Portas
porta_etcd_https: 2379
porta_etcd_peers: 2380
porta_etcd_metricas: 2381
porta_kubeapiserver: 6443
porta_haproxy_stats: 9000