# ansible/04-nfs/tasks/01-instalacao.yml
---
- name: Instalar pacote do NFS
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Criar diret√≥rio para compartilhamento
  ansible.builtin.file:
    path: /srv/nfs/k8s
    state: directory
    owner: nobody
    group: nobody
    mode: "0777"
